server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false  #开发环境将自我保护警告关闭
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/